trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- template: '../templates/yml/python/combo/setup-pip.yml'
- template: '../templates/yml/python/combo/run-pytest-ci.yml'
- template: '../templates/yml/python/steps/pycodestyle.yml'
