trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - templates/*

pr: none

pool:
  vmImage: 'Ubuntu-18.04'

variables:
- group: swellbot-github

steps:
- template: '../templates/yml/python/combo/setup-pip.yml'
- template: '../templates/yml/python/combo/run-pytest-ci.yml'
- template: '../templates/yml/python/steps/pycodestyle.yml'
