pr:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
    architecture: 'x64'

- script: python -m pip install --upgrade pip setuptools wheel
  displayName: 'Install tools'

- script: pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: pytest --junitxml=.testresults/unit/junit.xml
  displayName: 'Run tests'

- task: PublishTestResults@2
  displayName: 'Publish unit test results'
  inputs:
    testResultsFormat: JUnit
    testResultsFiles: 'junit.xml'
    searchFolder: $(Build.SourcesDirectory)/.testresults/unit
    testRunTitle: 'azure-pipelines-templates::Unit Tests::Build $(Build.BuildId)'
