pr:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- template: '../templates/yml/python/steps/set-version.yml'
- template: '../templates/yml/python/steps/update-tools.yml'
- template: '../templates/yml/python/steps/pip-install-dependencies.yml'

# - task: UsePythonVersion@0
#   inputs:
#     versionSpec: '3.7'
#     architecture: 'x64'

# - script: python -m pip install --upgrade pip setuptools wheel
#   displayName: 'Install tools'

# - script: pip install -r requirements.txt
#   displayName: 'Install dependencies'

- script: pycodestyle .
  displayName: 'Lint python'

- script: yamllint .
  displayName: 'Lint templates'
