pr:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: pip install -r requirements.txt
  displayName: 'Install Dependencies'

- script: pycodestyle .
  displayName: 'Lint Python'

- script: yamllint .
  displayName: 'Lint Templates'
